import { Tenant, User, Branch } from '@/types/tenant';

export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'Jindal IVF Centre',
    domain: 'jindalivf.com',
    logo: '/logos/jindal-ivf.png',
    primaryColor: '280 50% 35%',
    secondaryColor: '35 85% 55%',
    theme: {
      primaryColor: '280 50% 35%',
      secondaryColor: '35 85% 55%',
      accentColor: '45 95% 60%',
      brandName: 'Jindal IVF Centre',
      brandSlogan: 'The Joy of Parenthood',
      logo: '/logos/jindal-ivf.png',
    },
    subscription: {
      id: 'premium',
      name: 'Premium Plan',
      features: ['Unlimited Branches', 'IVF Tracking', 'Advanced Analytics', 'Telemedicine'],
      maxBranches: 999,
      maxUsers: 999,
      isActive: true,
      expiresAt: '2025-12-31',
    },
    branches: [
      {
        id: 'b1',
        tenantId: '1',
        name: 'Main Branch - Delhi',
        address: '123 Medical Center, Delhi',
        phone: '+91-11-12345678',
        email: 'delhi@jindalivf.com',
        isMainBranch: true,
        settings: {
          operatingHours: {
            monday: { open: '09:00', close: '18:00', isOpen: true },
            tuesday: { open: '09:00', close: '18:00', isOpen: true },
            wednesday: { open: '09:00', close: '18:00', isOpen: true },
            thursday: { open: '09:00', close: '18:00', isOpen: true },
            friday: { open: '09:00', close: '18:00', isOpen: true },
            saturday: { open: '09:00', close: '14:00', isOpen: true },
            sunday: { open: '00:00', close: '00:00', isOpen: false },
          },
          departments: ['IVF', 'Gynecology', 'Andrology', 'Laboratory'],
          services: ['IVF Treatment', 'IUI', 'Egg Freezing', 'Fertility Assessment'],
        },
      },
      {
        id: 'b2',
        tenantId: '1',
        name: 'Branch - Mumbai',
        address: '456 Healthcare Plaza, Mumbai',
        phone: '+91-22-87654321',
        email: 'mumbai@jindalivf.com',
        isMainBranch: false,
        settings: {
          operatingHours: {
            monday: { open: '08:00', close: '17:00', isOpen: true },
            tuesday: { open: '08:00', close: '17:00', isOpen: true },
            wednesday: { open: '08:00', close: '17:00', isOpen: true },
            thursday: { open: '08:00', close: '17:00', isOpen: true },
            friday: { open: '08:00', close: '17:00', isOpen: true },
            saturday: { open: '08:00', close: '13:00', isOpen: true },
            sunday: { open: '00:00', close: '00:00', isOpen: false },
          },
          departments: ['IVF', 'Gynecology', 'Laboratory'],
          services: ['IVF Treatment', 'IUI', 'Fertility Consultation'],
        },
      },
    ],
    settings: {
      timezone: 'Asia/Kolkata',
      dateFormat: 'DD/MM/YYYY',
      currency: 'INR',
      language: 'en',
      features: {
        appointments: true,
        ivfTracking: true,
        billing: true,
        inventory: true,
        reports: true,
        telemedicine: true,
      },
    },
  },
  {
    id: '2',
    name: 'Metro Hospital',
    domain: 'metrohospital.com',
    logo: '/logos/metro-hospital.png',
    primaryColor: '210 75% 45%',
    secondaryColor: '160 65% 50%',
    theme: {
      primaryColor: '210 75% 45%',
      secondaryColor: '160 65% 50%',
      accentColor: '50 90% 55%',
      brandName: 'Metro Hospital',
      brandSlogan: 'Healthcare Excellence',
      logo: '/logos/metro-hospital.png',
    },
    subscription: {
      id: 'standard',
      name: 'Standard Plan',
      features: ['Up to 5 Branches', 'Basic Analytics', 'Patient Management'],
      maxBranches: 5,
      maxUsers: 100,
      isActive: true,
      expiresAt: '2025-06-30',
    },
    branches: [
      {
        id: 'b3',
        tenantId: '2',
        name: 'Metro Hospital Main',
        address: '789 Central Avenue, Bangalore',
        phone: '+91-80-12345678',
        email: 'main@metrohospital.com',
        isMainBranch: true,
        settings: {
          operatingHours: {
            monday: { open: '07:00', close: '20:00', isOpen: true },
            tuesday: { open: '07:00', close: '20:00', isOpen: true },
            wednesday: { open: '07:00', close: '20:00', isOpen: true },
            thursday: { open: '07:00', close: '20:00', isOpen: true },
            friday: { open: '07:00', close: '20:00', isOpen: true },
            saturday: { open: '07:00', close: '15:00', isOpen: true },
            sunday: { open: '08:00', close: '14:00', isOpen: true },
          },
          departments: ['Emergency', 'Cardiology', 'Neurology', 'Orthopedics', 'General Medicine'],
          services: ['Emergency Care', 'Surgery', 'Diagnostics', 'Pharmacy'],
        },
      },
    ],
    settings: {
      timezone: 'Asia/Kolkata',
      dateFormat: 'DD/MM/YYYY',
      currency: 'INR',
      language: 'en',
      features: {
        appointments: true,
        ivfTracking: false,
        billing: true,
        inventory: true,
        reports: true,
        telemedicine: false,
      },
    },
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@jindalivf.com',
    name: 'Dr. Jindal',
    role: 'tenant_admin',
    tenantId: '1',
    branchId: 'b1',
    isActive: true,
    permissions: [
      { module: 'dashboard', actions: ['read'] },
      { module: 'patients', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'appointments', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'treatments', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'billing', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'reports', actions: ['read'] },
      { module: 'settings', actions: ['read', 'update'] },
    ],
  },
  {
    id: '2',
    email: 'doctor@jindalivf.com',
    name: 'Dr. Sarah Johnson',
    role: 'doctor',
    tenantId: '1',
    branchId: 'b1',
    isActive: true,
    permissions: [
      { module: 'dashboard', actions: ['read'] },
      { module: 'patients', actions: ['create', 'read', 'update'] },
      { module: 'appointments', actions: ['read', 'update'] },
      { module: 'treatments', actions: ['create', 'read', 'update'] },
    ],
  },
  {
    id: '3',
    email: 'receptionist@jindalivf.com',
    name: 'Priya Sharma',
    role: 'receptionist',
    tenantId: '1',
    branchId: 'b1',
    isActive: true,
    permissions: [
      { module: 'dashboard', actions: ['read'] },
      { module: 'patients', actions: ['create', 'read', 'update'] },
      { module: 'appointments', actions: ['create', 'read', 'update'] },
    ],
  },
  {
    id: '4',
    email: 'admin@metrohospital.com',
    name: 'Dr. Metro Admin',
    role: 'tenant_admin',
    tenantId: '2',
    branchId: 'b3',
    isActive: true,
    permissions: [
      { module: 'dashboard', actions: ['read'] },
      { module: 'patients', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'appointments', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'billing', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'reports', actions: ['read'] },
      { module: 'settings', actions: ['read', 'update'] },
    ],
  },
];

// Demo credentials for testing
export const demoCredentials = [
  { email: 'admin@jindalivf.com', password: 'admin123', name: 'Jindal IVF Admin' },
  { email: 'doctor@jindalivf.com', password: 'doctor123', name: 'Jindal IVF Doctor' },
  { email: 'receptionist@jindalivf.com', password: 'reception123', name: 'Jindal IVF Receptionist' },
  { email: 'admin@metrohospital.com', password: 'metro123', name: 'Metro Hospital Admin' },
];